# Usage: _site.<var name>
# Sample: _site.site_name
site_options:
  name: Mike
  site_name: MDL/Dart + SiteGen Sample
  author: Mike Mitterer

yaml_delimeter: ---

# Use secure connection
#usesec: true

cert_file: etc/dart.crt
key_file: etc/dart.key

# Disables sass and autprefixer 
usesass: false
autoprefixer: false